### PR TITLE
Return a sensible exit code

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by speed47** [comment]
Looking at exit codes, why not embracing the NRPE-defined version of exit codes for all modes after all?
We would just need to change the "error" exit code (currently 1) to someting else out of the NRPE-defined codes. 255?

**Comment by sylvestre** [comment]
cc @lamby

**Comment by lamby** [comment]
Go for it. Mine was an example patch :)

**Comment by lamby** [comment]
This is being tracked in Debian via https://bugs.debian.org/887077

**Comment by speed47** [comment]
Something like #77 ?

**Comment by speed47** [comment]
#77 merged

**Comment by lamby** [comment]
\o/

**Pull request closed without merging**
