### PR TITLE
improvements for xen systems

### PR DESCRIPTION
**Pull request by h0nIg**
there is no capability to detect mitigation on xen based systems, since they are not exposed properly via /sys/devices/system/cpu/vulnerabilities/l1tf (unknown state -> "Mitigation: PTE Inversion") and /proc/cpuinfo (missing flush_l1d flag)

see https://www.suse.com/support/kb/doc/?id=7023078

improve pti checks for dom0
see https://www.suse.com/support/kb/doc/?id=7022546

### CODE REVIEW

**Comment by speed47** [comment]
Thanks for your PR, and sorry for the delay!
I've rebased it over current `master` to fix conflicts.
I don't use Xen but reading your changes and the documentation, it looks good.
Please test on some Xen systems if you can, it would be good to have confirmation that it works well before I tag the next release!

**Comment by werk21** [comment]
With Xen 4.12 on Ubuntu 18.04 the hypervisor is not recognized. 
All pgrep-commands give empty results.
Only the grep-command for "hypervisor" in /proc/cpuinfo gives an positive result. (dmesg is truncated and will not help).
Kelly.

**Comment by werk21** [comment]
Maybe an pgrep for "xenstored" will help?

**Comment by speed47** [comment]
I tried to install Xen, after rebooting I had a qemu process so that's strange it's not catched on your system.
To be on the safe side, I added xenstored and xenconsoled, and also the 2 kthreads created by xen, xenbus and xenwatch.
Can you try with latest master?

**Comment by werk21** [comment]
Yes! Well done. Thank you very much:

> * This system is a host running a hypervisor:  YES

**Comment by werk21** [comment]
You added in your grep also xenbus and xenwatch in lines 3902 and 3908 - but they are running on DomU either. So every Xen-Guest ist recognised as Xen-Dom0. Can you please remove these two search-items? Thank you.

**Comment by speed47** [comment]
@werk21 removed in latest commit.

**Pull request merged**
